version: '3.9'
networks:
  default:
    external:
      name: local

services:
  flyway-runner:
    container_name: flyway-runner

    image: flyway/flyway:latest
    networks:
      - default
    depends_on:
      local-db-postgres:
        condition: service_healthy
    # command: migrate
    volumes:
      - ${PWD}/scripts:/flyway/sql
      - ${PWD}/conf:/flyway/conf

  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4
    networks:
      - default
    depends_on:
      local-db-postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-O",
          "-",
          "http://localhost:80/misc/ping"
        ]
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  local-db-postgres:
    container_name: local-db-postgres
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: dev
    networks:
      - default
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql-init:/docker-entrypoint-initdb.d/
      - ./backups:/var/lib/postgresql/backups
      - ./dumps:/var/lib/postgresql/dumps
volumes:
  pgdata:
  backups:
  dumps:
  sql-init:
  pgadmin-data: